//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyData
    {
        public short CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public byte LawID { get; set; }
        public decimal IssuedCapital { get; set; }
    
        public virtual LawType LawType { get; set; }
    }
}
